### ISSUE TITLE
Release plan

### ISSUE THREAD

**Issue by jdblischak** [r-lib/ghapps#1]
Thanks for developing this super useful package. It has saved me a bunch of time. I use it to add workflowr projects to [workflowr.io](https://workflowr.io/).

I see that you use the package to support your awesome R-universe project. Do you have plans to release it more widely? At minimum, would you be able to create a tag/release on GitHub?

By the way, please let me know if there is any way I can help you out with package maintenance.

**Comment by jeroen** [comment]
Yes I should. I think the plan was to clean up the API a bit before releasing but I never got to that yet....

**Comment by jdblischak** [comment]
Also FYI I investigated the failing CI (forked just prior to your recent commit). Looks like the main issue is `--as-cran`. It runs your `\dontrun` example. When I moved the example to the details section inside of a `\preformatted{}` block, then it failed due to a WARNING that there were no examples, tests, or vignettes. Thus if in the short-term you're not planning to submit to CRAN soon, the quickest fix would be to not enable the extra CRAN tests for now.

https://github.com/jdblischak/ghapps/commits/trigger-ci
https://github.com/jdblischak/ghapps/actions/workflows/R-CMD-check.yaml

**Comment by jeroen** [comment]
OK I overhauled the API and docs a bit to make it more suitable for public consumption. What do you think?

**Comment by jdblischak** [comment]
I think the updates in fb95a4f look great

**Comment by jeroen** [comment]
Version 1.0 is on CRAN now.

**Comment by jdblischak** [comment]
Thanks! This allowed me to easily add ghapps to conda-forge

https://github.com/conda-forge/r-ghapps-feedstock
